name: Deploy app to Docker Hub

on: 
 push:
  branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
    - uses: actions/checkout@v3

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: itsbijaya/django-app
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}